CREATE TABLE mesa
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador VARCHAR(255)                            NOT NULL,
    capacidade    INTEGER                                 NOT NULL,
    status        VARCHAR(255),
    CONSTRAINT pk_mesa PRIMARY KEY (id)
);

CREATE TABLE reserva
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id   BIGINT,
    mesa_id      BIGINT,
    data_reserva TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR(255),
    CONSTRAINT pk_reserva PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    senha VARCHAR(255)                            NOT NULL,
    role  VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE mesa
    ADD CONSTRAINT uc_mesa_identificador UNIQUE (identificador);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE reserva
    ADD CONSTRAINT FK_RESERVA_ON_MESA FOREIGN KEY (mesa_id) REFERENCES mesa (id);

ALTER TABLE reserva
    ADD CONSTRAINT FK_RESERVA_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);